Workarea.configure do |config|
  # Configuration for each JS file in the manifest. This allows
  # disabling certain modules from being loaded into the Sprockets
  # manifests on admin and storefront, so developers can focus on
  # rewriting the disabled modules.
  config.legacy_javascript = ActiveSupport::InheritableOptions.new(
    admin: ActiveSupport::InheritableOptions.new(
      libraries: %w(
        webcomponentsjs-rails/MutationObserver
        i18n
        i18n/translations
        strftime-rails/strftime
        local-time
        lodash
        jquery3
        jquery_ujs
        jquery_ujs/replace
        jquery-ui/core
        jquery-ui/widget
        jquery-ui/position
        jquery-ui/widgets/mouse
        jquery-ui/widgets/draggable
        jquery-ui/widgets/droppable
        jquery-ui/widgets/resizable
        jquery-ui/widgets/sortable
        jquery-ui/widgets/autocomplete
        jquery-ui/widgets/button
        jquery-ui/widgets/datepicker
        jquery-ui/widgets/menu
        jquery-ui/widgets/tabs
        jquery-ui/widgets/accordion
        tooltipster.bundle
        waypoints/noframework.waypoints
        waypoints/shortcuts/sticky
        select2
        wysihtml/
        wysihtml/toolbar
        wysihtml/all_commands
        jquery-unique-clone
        turbolinks
        spectrum
        Chart.bundle
        chartkick
        tribute
      ),
      templates: %w(
        workarea/core/templates/lorem_ipsum_view
        workarea/core/templates/hidden_input
        workarea/core/templates/reveal_password_button
        workarea/admin/templates/ui_menu_heading
        workarea/admin/templates/ui_menu_item
        workarea/admin/templates/loading
        workarea/admin/templates/message
        workarea/admin/templates/message_dismiss_action
        workarea/admin/templates/checkbox_with_label
        workarea/admin/templates/tabs_menu
        workarea/admin/templates/wysiwyg_toolbar
        workarea/admin/templates/content_block_iframe
        workarea/admin/templates/new_release_option
        workarea/admin/templates/remote_select
        workarea/admin/templates/help_helper
        workarea/admin/templates/help_helper_text
        workarea/admin/templates/takeover
        workarea/admin/templates/release_select_form
        workarea/admin/templates/bookmark_form
        workarea/admin/templates/inline_datepicker
        workarea/admin/templates/datetime_picker
        workarea/admin/templates/remote_select_sparkline
        workarea/admin/templates/remote_select_insight
        workarea/admin/templates/bulk_action_items_count
        workarea/admin/templates/direct_upload_processing
        workarea/admin/templates/direct_upload_table_row
        workarea/admin/templates/expandable_button
        workarea/admin/templates/jump_to_menu
        workarea/admin/templates/chart_legend
      ),
      library_extensions: %w(
        jquery_ui/admin/categorized_autocomplete
      ),
      configuration: %w(
        workarea/core/config
        workarea/admin/config
      ),
      routing: %w(
        workarea/core/routes
        workarea/admin/routes
      ),
      modules: %w(
        workarea/core/modules/transition_events
        workarea/core/modules/environment
        workarea/core/modules/cookie
        workarea/core/modules/string
        workarea/core/modules/url
        workarea/core/modules/image
        workarea/core/modules/deletion_forms
        workarea/core/modules/form_submitting_controls
        workarea/core/modules/jquery
        workarea/core/modules/style_guide_empty_links
        workarea/core/modules/style_guide_accordions
        workarea/core/modules/reveal_password
        workarea/core/modules/local_time
        workarea/core/modules/date
        workarea/core/modules/copy_to_clipboard
        workarea/admin/modules/style_guide_autocomplete_fields
        workarea/admin/modules/categorized_autocomplete_fields
        workarea/admin/modules/messages
        workarea/admin/modules/takeover
        workarea/admin/modules/autocomplete_fields
        workarea/admin/modules/new_navigation_taxons
        workarea/admin/modules/cloneable_rows
        workarea/admin/modules/datetimepicker_fields
        workarea/admin/modules/datepicker_fields
        workarea/admin/modules/tabs
        workarea/admin/modules/wysiwygs
        workarea/admin/modules/discount_options_menus
        workarea/admin/modules/asset_pickers
        workarea/admin/modules/product_images_sortables
        workarea/admin/modules/menu_editor_links
        workarea/admin/modules/menu_editor_menu_list_sortables
        workarea/admin/modules/menu_editor_sort_by_menus
        workarea/admin/modules/recommendations_sortables
        workarea/admin/modules/publish_with_release_menus
        workarea/admin/modules/releasable_model_search_forms
        workarea/admin/modules/toggle_buttons
        workarea/admin/modules/remote_selects
        workarea/admin/modules/release_calendar_placeholders
        workarea/admin/modules/calendars
        workarea/admin/modules/bulk_action_items
        workarea/admin/modules/bulk_action_deletion
        workarea/admin/modules/property_toggles
        workarea/admin/modules/help_helper
        workarea/admin/modules/primary_nav
        workarea/admin/modules/taxon_select
        workarea/admin/modules/dom_remove
        workarea/admin/modules/featured_products_sort
        workarea/admin/modules/taxon_insert
        workarea/admin/modules/add_content_block_buttons
        workarea/admin/modules/content_editor
        workarea/admin/modules/content_blocks
        workarea/admin/modules/content_editor_forms
        workarea/admin/modules/content_editor_form_cancel
        workarea/admin/modules/content_block_list
        workarea/admin/modules/content_preview
        workarea/admin/modules/content_preset_form
        workarea/admin/modules/bookmarks
        workarea/admin/modules/sort_navigation_menus
        workarea/admin/modules/asset_picker_fields
        workarea/admin/modules/filter_dropdowns
        workarea/admin/modules/toggle_filters
        workarea/admin/modules/release_reminder
        workarea/admin/modules/relevance_sort
        workarea/admin/modules/tooltips
        workarea/admin/modules/publish_create_release
        workarea/admin/modules/product_rules_preview
        workarea/admin/modules/sort_variants
        workarea/admin/modules/copy_ids
        workarea/admin/modules/disable_publish_now
        workarea/admin/modules/unsaved_changes
        workarea/admin/modules/add_to_calendar_buttons
        workarea/admin/modules/range_fields
        workarea/admin/modules/direct_uploads
        workarea/admin/modules/pricing_overrides
        workarea/admin/modules/expandables
        workarea/admin/modules/impersonation_notification
        workarea/admin/modules/timeline_report_chart
        workarea/admin/modules/jump_to_menus
        workarea/admin/modules/active_by_segment_tooltips
        workarea/admin/modules/toggle_elements
        workarea/admin/modules/selects
        workarea/admin/modules/tribute_areas
      )
    ),
    storefront: ActiveSupport::InheritableOptions.new(
      libraries: %w(
        webcomponentsjs-rails/MutationObserver
        i18n
        i18n/translations
        local-time
        lodash
        jquery3
        jquery-ui/core
        jquery-ui/widget
        jquery-ui/position
        jquery-ui/widgets/mouse
        jquery-ui/widgets/draggable
        jquery-ui/widgets/resizable
        jquery-ui/widgets/button
        jquery-ui/widgets/dialog
        jquery-ui/widgets/menu
        jquery.validate
        jquery.validate.additional-methods
        waypoints/noframework.waypoints
        waypoints/shortcuts/sticky
        jquery-unique-clone
        jquery_ujs
      ),
      templates: %w(
        workarea/core/templates/lorem_ipsum_view
        workarea/core/templates/reveal_password_button
        workarea/storefront/templates/loading
        workarea/storefront/templates/message
        workarea/storefront/templates/message_dismiss_action
        workarea/storefront/templates/button
        workarea/storefront/templates/same_as_shipping_button_property
        workarea/storefront/templates/saved_addresses_property
        workarea/storefront/templates/log_out_link
        workarea/storefront/templates/page_header_cart_count
        workarea/storefront/templates/pagination_button
        workarea/storefront/templates/back_to_top_button
        workarea/storefront/templates/authenticity_token
        workarea/storefront/templates/mobile_filters_nav_close_button
        workarea/storefront/templates/optional_field_prompt
      ),
      configuration:   %w(
        workarea/core/config
        workarea/storefront/config
      ),
      routing: %w(
        workarea/core/routes
        workarea/storefront/routes
      ),
      modules: %w(
        workarea/core/modules/transition_events
        workarea/core/modules/environment
        workarea/core/modules/cookie
        workarea/core/modules/string
        workarea/core/modules/url
        workarea/core/modules/image
        workarea/core/modules/deletion_forms
        workarea/core/modules/form_submitting_controls
        workarea/core/modules/jquery
        workarea/core/modules/style_guide_empty_links
        workarea/core/modules/reveal_password
        workarea/core/modules/local_time
        workarea/storefront/modules/forms
        workarea/storefront/modules/authenticity_token
        workarea/storefront/modules/dialog
        workarea/storefront/modules/dialog_buttons
        workarea/storefront/modules/dialog_forms
        workarea/storefront/modules/dialog_close_buttons
        workarea/storefront/modules/loading
        workarea/storefront/modules/messages
        workarea/storefront/modules/pagination
        workarea/storefront/modules/current_user
        workarea/storefront/modules/break_points
        workarea/storefront/modules/primary_nav_content
        workarea/storefront/modules/product_details_sku_selects
        workarea/storefront/modules/popup_buttons
        workarea/storefront/modules/alternate_image_buttons
        workarea/storefront/modules/scroll_to_buttons
        workarea/storefront/modules/address_region_fields
        workarea/storefront/modules/checkout_addresses_forms
        workarea/storefront/modules/checkout_shipping_services
        workarea/storefront/modules/checkout_primary_payments
        workarea/storefront/modules/single_submit_forms
        workarea/storefront/modules/log_out_link_placeholders
        workarea/storefront/modules/admin_toolbar
        workarea/storefront/modules/analytics
        workarea/storefront/modules/cart_count
        workarea/storefront/modules/recommendations_placeholders
        workarea/storefront/modules/workarea_analytics
        workarea/storefront/modules/mobile_nav_button
        workarea/storefront/modules/back_to_top_button
        workarea/storefront/modules/mobile_filter_buttons
        workarea/storefront/modules/option_buttons
        workarea/storefront/modules/optional_fields
        workarea/storefront/modules/traffic_referrer
        workarea/storefront/modules/lazy_images
        workarea/storefront/modules/privacy_popup
      )
    )
  )
end
